# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2016-12-08 09:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompleteToolbox',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('description', models.CharField(blank=True, help_text='The Subitle', max_length=100, null=True)),
                ('date_start', models.DateField(blank=True, help_text='The Date', null=True)),
                ('date_end', models.DateField(blank=True, help_text='The Date (END)', null=True)),
            ],
            options={
                'verbose_name': 'Complete Toolbox',
            },
        ),
        migrations.CreateModel(
            name='FilerToolbox',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Filer Toolbox',
            },
        ),
        migrations.CreateModel(
            name='SimpleTool',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('description', models.CharField(blank=True, help_text='The Subitle', max_length=100, null=True)),
                ('date_start', models.DateField(blank=True, help_text='The Date', null=True)),
                ('date_end', models.DateField(blank=True, help_text='The Date (END)', null=True)),
            ],
            options={
                'verbose_name': 'Simple Tool',
            },
        ),
        migrations.CreateModel(
            name='SimpleTool2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('description', models.CharField(blank=True, help_text='The Subitle', max_length=100, null=True)),
                ('date_start', models.DateField(blank=True, help_text='The Date', null=True)),
                ('date_end', models.DateField(blank=True, help_text='The Date (END)', null=True)),
            ],
            options={
                'verbose_name': 'Simple Tool (Inlines)',
                'verbose_name_plural': 'Simple Tool (Inlines)',
            },
        ),
        migrations.CreateModel(
            name='ToolboxItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_added', models.DateTimeField(auto_now=True)),
                ('document', models.FileField(blank=True, null=True, upload_to=b'')),
                ('tool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='toolbox.SimpleTool')),
                ('toolbox', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='toolbox.CompleteToolbox')),
            ],
        ),
        migrations.AddField(
            model_name='completetoolbox',
            name='tool',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='toolbox.SimpleTool'),
        ),
        migrations.AddField(
            model_name='completetoolbox',
            name='tools',
            field=models.ManyToManyField(blank=True, null=True, to='toolbox.SimpleTool2'),
        ),
    ]
