# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2016-12-08 09:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toolbox', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='completetoolbox',
            name='tools',
            field=models.ManyToManyField(blank=True, to='toolbox.SimpleTool2'),
        ),
    ]
