# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2016-12-08 09:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('toolbox', '0002_auto_20161208_1024'),
    ]

    operations = [
        migrations.AddField(
            model_name='completetoolbox',
            name='tool_raw',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='toolboxes_raw', to='toolbox.SimpleTool'),
        ),
        migrations.AddField(
            model_name='completetoolbox',
            name='tools_horizontal',
            field=models.ManyToManyField(blank=True, related_name='toolboxes_b', to='toolbox.SimpleTool2'),
        ),
        migrations.AddField(
            model_name='completetoolbox',
            name='tools_radio_horizontal',
            field=models.ManyToManyField(blank=True, related_name='toolboxes_e', to='toolbox.SimpleTool2'),
        ),
        migrations.AddField(
            model_name='completetoolbox',
            name='tools_radio_vertical',
            field=models.ManyToManyField(blank=True, related_name='toolboxes_d', to='toolbox.SimpleTool2'),
        ),
        migrations.AddField(
            model_name='completetoolbox',
            name='tools_through',
            field=models.ManyToManyField(blank=True, related_name='toolboxes_f', through='toolbox.ToolboxItem', to='toolbox.SimpleTool'),
        ),
        migrations.AddField(
            model_name='completetoolbox',
            name='tools_vertical',
            field=models.ManyToManyField(blank=True, related_name='toolboxes_c', to='toolbox.SimpleTool2'),
        ),
        migrations.AlterField(
            model_name='completetoolbox',
            name='tool',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='toolboxes', to='toolbox.SimpleTool'),
        ),
        migrations.AlterField(
            model_name='completetoolbox',
            name='tools',
            field=models.ManyToManyField(blank=True, related_name='toolboxes', to='toolbox.SimpleTool2'),
        ),
    ]
