# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2016-12-08 09:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toolbox', '0003_auto_20161208_1033'),
    ]

    operations = [
        migrations.AddField(
            model_name='completetoolbox',
            name='datetime_end',
            field=models.DateField(blank=True, help_text='The Date (END)', null=True),
        ),
        migrations.AddField(
            model_name='completetoolbox',
            name='datetime_start',
            field=models.DateField(blank=True, help_text='The Date', null=True),
        ),
    ]
