# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2016-12-08 09:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('toolbox', '0004_auto_20161208_1035'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='completetoolbox',
            name='tools_radio_horizontal',
        ),
        migrations.RemoveField(
            model_name='completetoolbox',
            name='tools_radio_vertical',
        ),
    ]
