# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2016-12-08 09:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('toolbox', '0005_auto_20161208_1036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='completetoolbox',
            name='tool',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='toolboxes_fk_a', to='toolbox.SimpleTool'),
        ),
        migrations.AlterField(
            model_name='completetoolbox',
            name='tool_raw',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='toolboxes_fk_b', to='toolbox.SimpleTool'),
        ),
    ]
