# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2016-12-08 09:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('toolbox', '0006_auto_20161208_1038'),
    ]

    operations = [
        migrations.AddField(
            model_name='completetoolbox',
            name='tool_radio_horizontal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='toolboxes_fk_d', to='toolbox.SimpleTool2'),
        ),
        migrations.AddField(
            model_name='completetoolbox',
            name='tool_radio_vertical',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='toolboxes_fk_c', to='toolbox.SimpleTool2'),
        ),
    ]
