# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2016-12-08 09:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toolbox', '0008_auto_20161208_1042'),
    ]

    operations = [
        migrations.AddField(
            model_name='completetoolbox',
            name='duration',
            field=models.DurationField(blank=True, help_text='And some words about how to use "this" field.', null=True),
        ),
        migrations.AddField(
            model_name='completetoolbox',
            name='is_active',
            field=models.BooleanField(default=False, help_text='And some words about how to use "this" field.'),
        ),
        migrations.AddField(
            model_name='completetoolbox',
            name='is_nice',
            field=models.NullBooleanField(help_text='And some words about how to use "this" field.'),
        ),
        migrations.AddField(
            model_name='completetoolbox',
            name='time',
            field=models.TimeField(blank=True, help_text='And some words about how to use "this" field.', null=True),
        ),
    ]
