# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2016-12-08 09:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import filer.fields.file
import filer.fields.folder
import filer.fields.image


class Migration(migrations.Migration):

    dependencies = [
        ('filer', '0006_auto_20160623_1627'),
        ('toolbox', '0009_auto_20161208_1049'),
    ]

    operations = [
        migrations.AddField(
            model_name='completetoolbox',
            name='document',
            field=models.FileField(blank=True, help_text='And some words about how to use "this" field.', null=True, upload_to=b''),
        ),
        migrations.AddField(
            model_name='completetoolbox',
            name='filer_directory',
            field=filer.fields.folder.FilerFolderField(blank=True, help_text='And some words about how to use "this" field.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='toolboxees_filer_c', to='filer.Folder'),
        ),
        migrations.AddField(
            model_name='completetoolbox',
            name='filer_document',
            field=filer.fields.file.FilerFileField(blank=True, help_text='And some words about how to use "this" field.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='toolboxees_filer_a', to='filer.File'),
        ),
        migrations.AddField(
            model_name='completetoolbox',
            name='filer_image',
            field=filer.fields.image.FilerImageField(blank=True, help_text='And some words about how to use "this" field.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='toolboxees_filer_b', to='filer.Image'),
        ),
        migrations.AddField(
            model_name='completetoolbox',
            name='image',
            field=models.ImageField(blank=True, help_text='And some words about how to use "this" field.', null=True, upload_to=b''),
        ),
    ]
