# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2016-12-08 10:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import filer.fields.file
import filer.fields.folder
import filer.fields.image


class Migration(migrations.Migration):

    dependencies = [
        ('filer', '0006_auto_20160623_1627'),
        ('toolbox', '0010_auto_20161208_1054'),
    ]

    operations = [
        migrations.CreateModel(
            name='InlineToolbox',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='And some words about how to use "this" field.', max_length=100, null=True)),
                ('description', models.CharField(blank=True, help_text='And some words about how to use "this" field.', max_length=100, null=True)),
                ('long_description', models.TextField(blank=True, help_text='And some words about how to use "this" field.', null=True)),
                ('is_active', models.BooleanField(default=False, help_text='And some words about how to use "this" field.')),
                ('is_nice', models.NullBooleanField(help_text='And some words about how to use "this" field.')),
                ('date_start', models.DateField(blank=True, help_text='And some words about how to use "this" field.', null=True)),
                ('date_end', models.DateField(blank=True, help_text='And some words about how to use "this" field.', null=True)),
                ('datetime_start', models.DateField(blank=True, help_text='And some words about how to use "this" field.', null=True)),
                ('datetime_end', models.DateField(blank=True, help_text='And some words about how to use "this" field.', null=True)),
                ('time', models.TimeField(blank=True, help_text='And some words about how to use "this" field.', null=True)),
                ('duration', models.DurationField(blank=True, help_text='And some words about how to use "this" field.', null=True)),
                ('document', models.FileField(blank=True, help_text='And some words about how to use "this" field.', null=True, upload_to=b'')),
                ('image', models.ImageField(blank=True, help_text='And some words about how to use "this" field.', null=True, upload_to=b'')),
                ('filer_directory', filer.fields.folder.FilerFolderField(blank=True, help_text='And some words about how to use "this" field.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='toolbox_inlinetoolbox_filer_c', to='filer.Folder')),
                ('filer_document', filer.fields.file.FilerFileField(blank=True, help_text='And some words about how to use "this" field.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='toolbox_inlinetoolbox_filer_a', to='filer.File')),
                ('filer_image', filer.fields.image.FilerImageField(blank=True, help_text='And some words about how to use "this" field.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='toolbox_inlinetoolbox_filer_b', to='filer.Image')),
                ('tool', models.ForeignKey(blank=True, help_text='And some words about how to use "this" field.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='toolbox_inlinetoolbox_fk_a', to='toolbox.SimpleTool')),
                ('tool_radio_horizontal', models.ForeignKey(blank=True, help_text='And some words about how to use "this" field.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='toolbox_inlinetoolbox_fk_d', to='toolbox.SimpleTool2')),
                ('tool_radio_vertical', models.ForeignKey(blank=True, help_text='And some words about how to use "this" field.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='toolbox_inlinetoolbox_fk_c', to='toolbox.SimpleTool2')),
                ('tool_raw', models.ForeignKey(blank=True, help_text='And some words about how to use "this" field.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='toolbox_inlinetoolbox_fk_b', to='toolbox.SimpleTool')),
                ('tools', models.ManyToManyField(blank=True, help_text='And some words about how to use "this" field.', related_name='toolbox_inlinetoolboxbox', to='toolbox.SimpleTool2')),
                ('tools_horizontal', models.ManyToManyField(blank=True, help_text='And some words about how to use "this" field.', related_name='toolbox_inlinetoolbox_b', to='toolbox.SimpleTool2')),
            ],
            options={
                'verbose_name': 'InlineToolbox Toolbox',
            },
        ),
        migrations.RemoveField(
            model_name='completetoolbox',
            name='tool',
        ),
        migrations.RemoveField(
            model_name='completetoolbox',
            name='tool_radio_horizontal',
        ),
        migrations.RemoveField(
            model_name='completetoolbox',
            name='tool_radio_vertical',
        ),
        migrations.RemoveField(
            model_name='completetoolbox',
            name='tool_raw',
        ),
        migrations.RemoveField(
            model_name='completetoolbox',
            name='tools',
        ),
        migrations.RemoveField(
            model_name='completetoolbox',
            name='tools_horizontal',
        ),
        migrations.RemoveField(
            model_name='completetoolbox',
            name='tools_through',
        ),
        migrations.RemoveField(
            model_name='completetoolbox',
            name='tools_vertical',
        ),
        migrations.AlterField(
            model_name='completetoolbox',
            name='filer_directory',
            field=filer.fields.folder.FilerFolderField(blank=True, help_text='And some words about how to use "this" field.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='toolbox_completetoolbox_filer_c', to='filer.Folder'),
        ),
        migrations.AlterField(
            model_name='completetoolbox',
            name='filer_document',
            field=filer.fields.file.FilerFileField(blank=True, help_text='And some words about how to use "this" field.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='toolbox_completetoolbox_filer_a', to='filer.File'),
        ),
        migrations.AlterField(
            model_name='completetoolbox',
            name='filer_image',
            field=filer.fields.image.FilerImageField(blank=True, help_text='And some words about how to use "this" field.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='toolbox_completetoolbox_filer_b', to='filer.Image'),
        ),
        migrations.AlterField(
            model_name='toolboxitem',
            name='toolbox',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='toolbox.InlineToolbox'),
        ),
        migrations.AddField(
            model_name='inlinetoolbox',
            name='tools_through',
            field=models.ManyToManyField(blank=True, help_text='And some words about how to use "this" field.', related_name='toolbox_inlinetoolbox_f', through='toolbox.ToolboxItem', to='toolbox.SimpleTool'),
        ),
        migrations.AddField(
            model_name='inlinetoolbox',
            name='tools_vertical',
            field=models.ManyToManyField(blank=True, help_text='And some words about how to use "this" field.', related_name='toolbox_inlinetoolbox_c', to='toolbox.SimpleTool2'),
        ),
    ]
