# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2016-12-08 10:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('toolbox', '0012_auto_20161208_1144'),
    ]

    operations = [
        migrations.CreateModel(
            name='InlineToolbox',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'inline Toolbox',
            },
        ),
        migrations.CreateModel(
            name='ToolboxInlineItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_added', models.DateTimeField(auto_now=True)),
                ('document', models.FileField(blank=True, null=True, upload_to=b'')),
                ('tool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='toolbox.SimpleTool')),
                ('toolbox', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='toolbox.InlineToolbox')),
            ],
        ),
        migrations.AlterModelOptions(
            name='relationtoolbox',
            options={'verbose_name': 'Relation Toolbox'},
        ),
        migrations.AddField(
            model_name='inlinetoolbox',
            name='tools_through',
            field=models.ManyToManyField(blank=True, help_text='And some words about how to use "this" field.', related_name='toolbox_inlinetoolbox_f', through='toolbox.ToolboxInlineItem', to='toolbox.SimpleTool'),
        ),
    ]
