# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2016-12-08 11:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import filer.fields.file
import filer.fields.image


class Migration(migrations.Migration):

    dependencies = [
        ('filer', '0006_auto_20160623_1627'),
        ('toolbox', '0014_auto_20161208_1158'),
    ]

    operations = [
        migrations.CreateModel(
            name='InlineFilerFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(help_text='And some words about how to use "this" field.', max_length=64, null=True)),
                ('file', filer.fields.file.FilerFileField(help_text='And some words about how to use "this" field.', on_delete=django.db.models.deletion.CASCADE, to='filer.File')),
            ],
        ),
        migrations.CreateModel(
            name='InlineFilerImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(help_text='And some words about how to use "this" field.', max_length=64, null=True)),
                ('date', models.DateField(blank=True, help_text='And some words about how to use "this" field.', null=True)),
                ('image', filer.fields.image.FilerImageField(help_text='And some words about how to use "this" field.', on_delete=django.db.models.deletion.CASCADE, to='filer.Image')),
            ],
        ),
        migrations.AlterField(
            model_name='toolboxinlineitem',
            name='document',
            field=models.FileField(blank=True, help_text='And some words about how to use "this" field.', null=True, upload_to=b''),
        ),
        migrations.AlterField(
            model_name='toolboxinlineitem',
            name='time_added',
            field=models.DateTimeField(blank=True, help_text='And some words about how to use "this" field.', null=True),
        ),
        migrations.AlterField(
            model_name='toolboxinlineitem',
            name='tool',
            field=models.ForeignKey(help_text='And some words about how to use "this" field.', on_delete=django.db.models.deletion.CASCADE, to='toolbox.SimpleTool'),
        ),
    ]
