# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2016-12-07 14:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cupboard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Cupboard',
                'verbose_name_plural': 'Cupboards',
            },
        ),
        migrations.CreateModel(
            name='CupboardTranslation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Claim')),
                ('description', models.TextField(blank=True, max_length=100, null=True, verbose_name='Description')),
                ('language_code', models.CharField(db_index=True, max_length=15)),
                ('master', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='kitchensink.Cupboard')),
            ],
            options={
                'managed': True,
                'abstract': False,
                'db_table': 'kitchensink_cupboard_translation',
                'db_tablespace': '',
                'default_permissions': (),
            },
        ),
        migrations.AlterUniqueTogether(
            name='cupboardtranslation',
            unique_together=set([('language_code', 'master')]),
        ),
    ]
