# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2016-12-07 15:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kitchensink', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cupboard',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=b'', verbose_name='last time cleaned'),
        ),
        migrations.AddField(
            model_name='cupboard',
            name='last_time_cleaned',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last time cleaned'),
        ),
    ]
