# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2016-12-07 16:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kitchensink', '0002_auto_20161207_1632'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appliance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True, verbose_name='name')),
                ('image', models.ImageField(blank=True, null=True, upload_to=b'', verbose_name='picture')),
                ('color', models.IntegerField(choices=[(1, 'red'), (2, 'blue')], verbose_name='color')),
            ],
            options={
                'verbose_name': 'Appliance',
                'verbose_name_plural': 'Appliances',
            },
        ),
        migrations.AddField(
            model_name='cupboard',
            name='color',
            field=models.IntegerField(choices=[(1, 'red'), (2, 'blue')], default=1, verbose_name='color'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cupboard',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=b'', verbose_name='picture'),
        ),
        migrations.AlterField(
            model_name='cupboardtranslation',
            name='name',
            field=models.CharField(max_length=100, null=True, verbose_name='name'),
        ),
    ]
