# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2016-12-07 20:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kitchensink', '0003_auto_20161207_1709'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appliance',
            name='name',
        ),
        migrations.AddField(
            model_name='appliance',
            name='model',
            field=models.CharField(max_length=100, null=True, verbose_name='model'),
        ),
        migrations.AddField(
            model_name='appliance',
            name='type',
            field=models.CharField(blank=True, choices=[('fridge', 'fridge')], max_length=32, null=True, verbose_name='type'),
        ),
    ]
