# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2016-12-07 20:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kitchensink', '0004_auto_20161207_2141'),
    ]

    operations = [
        migrations.AddField(
            model_name='appliance',
            name='brand',
            field=models.CharField(max_length=100, null=True, verbose_name='brand'),
        ),
        migrations.AlterField(
            model_name='appliance',
            name='color',
            field=models.IntegerField(blank=True, choices=[(1, 'red'), (2, 'blue')], null=True, verbose_name='color'),
        ),
        migrations.AlterField(
            model_name='appliance',
            name='model',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='model'),
        ),
        migrations.AlterField(
            model_name='cupboard',
            name='color',
            field=models.IntegerField(blank=True, choices=[(1, 'red'), (2, 'blue')], null=True, verbose_name='color'),
        ),
    ]
