# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2016-12-07 20:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kitchensink', '0005_auto_20161207_2145'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplianceService',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('notes', models.TextField()),
                ('appliance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kitchensink.Appliance')),
            ],
            options={
                'verbose_name': 'Service',
                'verbose_name_plural': 'Services',
            },
        ),
    ]
