# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2016-12-07 20:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kitchensink', '0006_applianceservice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applianceservice',
            name='notes',
            field=models.CharField(max_length=128),
        ),
    ]
