# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2016-12-07 21:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kitchensink', '0009_auto_20161207_2214'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sink',
            name='subtitle_b',
        ),
        migrations.RemoveField(
            model_name='sink',
            name='title_b',
        ),
        migrations.AddField(
            model_name='sink',
            name='date_end',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sink',
            name='date_start',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sink',
            name='datetime_end',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sink',
            name='datetime_start',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
