# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2016-12-07 21:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kitchensink', '0010_auto_20161207_2217'),
    ]

    operations = [
        migrations.CreateModel(
            name='SinkBit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='The Title', max_length=100, null=True)),
                ('subtitle', models.CharField(blank=True, help_text='The Subitle', max_length=100, null=True)),
                ('date_start', models.DateField(blank=True, help_text='The Date', null=True)),
                ('datetime_start', models.DateTimeField(blank=True, help_text='The Datetime', null=True)),
                ('date_end', models.DateField(blank=True, help_text='The Date (END)', null=True)),
                ('datetime_end', models.DateTimeField(blank=True, help_text='The Datetime (END)', null=True)),
            ],
            options={
                'verbose_name': 'Sink Bit',
                'verbose_name_plural': 'Sink Bits',
            },
        ),
        migrations.AlterField(
            model_name='sink',
            name='date_end',
            field=models.DateField(blank=True, help_text='The Date (END)', null=True),
        ),
        migrations.AlterField(
            model_name='sink',
            name='date_start',
            field=models.DateField(blank=True, help_text='The Date', null=True),
        ),
        migrations.AlterField(
            model_name='sink',
            name='datetime_end',
            field=models.DateTimeField(blank=True, help_text='The Datetime (END)', null=True),
        ),
        migrations.AlterField(
            model_name='sink',
            name='datetime_start',
            field=models.DateTimeField(blank=True, help_text='The Datetime', null=True),
        ),
        migrations.AlterField(
            model_name='sink',
            name='subtitle',
            field=models.CharField(blank=True, help_text='The Subitle', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='sink',
            name='title',
            field=models.CharField(help_text='The Title', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='sinkbit',
            name='sink',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kitchensink.Sink'),
        ),
    ]
